CREATE TABLE "TBL_USER" 
   (	
    "USER_ID" NUMBER NOT NULL, 
	"PF_ID" VARCHAR2(100) NOT NULL,	
    "USERNAME" VARCHAR2(100),
	"MAIL_ID" VARCHAR2(100), 
	"PHONENO" VARCHAR2(20), 	
	"ROLE" VARCHAR2(10), 	
	"CIRCLE" VARCHAR2(100), 
    "REPORTING_AUTHORITY_NAME" VARCHAR2(100), 
    "REPORTING_AUTHORITY_EMAIL"  VARCHAR2(100), 
	"ENABLED" VARCHAR2(1), 
	"FIRSTNAME" VARCHAR2(100), 	
	"LASTNAME" VARCHAR2(100), 
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("USER_ID")	
   );

CREATE TABLE "TBL_KIOSK_MASTER" 
   (	
    "ID" NUMBER,
	"SR_NO" NUMBER,
    "KIOSK_ID" VARCHAR2(100), 
	"VENDOR" VARCHAR2(100), 
	"INSTALLATION_DATE" DATE, 
	"KIOSK_IP" VARCHAR2(100), 
	"KIOSK_MAC_ADDRESS" VARCHAR2(100), 
	"SITE_TYPE" VARCHAR2(100), 
	"LOCATION" VARCHAR2(1000), 
	"ADDRESS" VARCHAR2(3000), 
	"BRANCH_CODE" VARCHAR2(100), 
	"KIOSK_SERIAL_NO" VARCHAR2(100),
	"CIRCLE" VARCHAR2(100),
	"BRANCH_NAME" VARCHAR2(100),
	"OS" VARCHAR2(100),
	"MAKE" VARCHAR2(100),
	"INSTALLATION_STATUS" VARCHAR2(100),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("ID")	
   );

CREATE TABLE "TBL_BRANCH_MASTER" 
   (	
    "BR_ID" NUMBER, 
	"CIRCLE" VARCHAR2(100), 
	"CRCL_NAME" VARCHAR2(100), 
	"NETWORK" VARCHAR2(100), 
	MOD_CODE VARCHAR2(100),               
	"MODULE" VARCHAR2(100), 
	"REGION" VARCHAR2(100), 
	"BRANCH_CODE" VARCHAR2(100), 
	"BRANCH_NAME" VARCHAR2(100),
	CRCL_CODE VARCHAR2(100),
	POP_GROUP VARCHAR2(100),
	POP_DESC VARCHAR2(100),	
	OPEN_CLOSE_STATUS VARCHAR2(100),
	OPENDT VARCHAR2(100),
	STAT_CODE VARCHAR2(100),	
	STAT_DESC VARCHAR2(1000),	
	DIST_CODE VARCHAR2(100),	
	DIST_DESC VARCHAR2(1000),	
	ADDRESS1 VARCHAR2(10),	
	ADDRESS2 VARCHAR2(3000),	
	ADDRESS3 VARCHAR2(3000),
	ADDRESS4 VARCHAR2(3000),	
	PINCODE VARCHAR2(100),	
	STD_CODE VARCHAR2(100),	
	PHONE VARCHAR2(100),
	MICR_CODE VARCHAR2(100),	
	IFSC VARCHAR2(100),
	EMAIL VARCHAR2(100),	
	BRANCHMGR_NAME VARCHAR2(100),	
	BRANCHMGR_MOBILE VARCHAR2(100),
	BUSINESSHRS VARCHAR2(100),	
	OFFICE_TYPE VARCHAR2(1000),
	OFFICE_DESC VARCHAR2(1000),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("BR_ID")	
   );

CREATE TABLE "TBL_CALL_TYPE" 
   (	
    "CATEGORY" VARCHAR2(1000), 
	"SUB_CATEGORY" VARCHAR2(2000), 
	"RISK" VARCHAR2(100)
   );
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','Incorrect Username or Password','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','Operating system is not loaded','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','Password has expired','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Myler strip replacement/ Noise gear issue','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Printer - Catridge Ink is Low/Over','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','Auto Lock / Sleep mode','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','AD Domain Joining','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','User not permitted to login to this Machine','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','AD Trust Relationship issue','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Passbook Printer Cover Open','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Keyboard/Mouse  not working','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Printer Offline','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Touch screen not working','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Hardware','Passbook Jam in Printer','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Operating System','Configure AutoLogon','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Kiosk Application','Application crashing Intermittently','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Printing','Incorrect data being printed','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Kiosk Application','RMS/RMMS Agent is not connected','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Printing','Slow Printing','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Kiosk Application','Application Hang','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Connectivity','LAN connecitivity is not available','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Printing','Incorrect alignment','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Printing','Transactions are missing','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Kiosk Application','Application is showing maintainence mode','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Printing','Repeated/Old data printing','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Connectivity','No Connectivity at this moment(PBK004/EC001)','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Connectivity','Linux OS Kiosk - Permanent Whitelisting','High');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Barcode','Inactive Barcode','Low');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Barcode','Invalid Barcode','Low');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Barcode','Barcode scanning failure in subsequent attempt','Medium');
Insert into TBL_CALL_TYPE (CATEGORY,SUB_CATEGORY,RISK) values ('Barcode','Barcode Not Found','Medium');

CREATE TABLE "TBL_CMS_CMF_MAPPING" 
   (	"USER_ID" NUMBER, 
	"CMS_USERNAME" VARCHAR2(1000 BYTE), 
	"CMF_USERNAME" VARCHAR2(1000 BYTE)
   );


CREATE TABLE "TBL_MANUAL_CALL_LOG" 
   (	
    "MANUAL_CALL_LOG_ID" VARCHAR2(1000), 
	"BRANCH_CODE" VARCHAR2(100), 
	"KIOSK_ID" VARCHAR2(100), 
	"VENDOR" VARCHAR2(100), 
	"BRANCH_NAME" VARCHAR2(100), 
	"CONTACT_PERSON" VARCHAR2(100), 
	"CONTACT_NO" VARCHAR2(20), 
	"ERROR" VARCHAR2(1000), 
	"AGENT_STATUS" VARCHAR2(200), 
	"COMMENTS" VARCHAR2(3000), 
	"KIOSK_SERIAL_NO" VARCHAR2(100), 
	"CALL_CATEGORY" VARCHAR2(1000), 
	"CALL_SUBCATEGORY" VARCHAR2(2000), 
	"EMAIL" VARCHAR2(100),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("MANUAL_CALL_LOG_ID")	
   ); 

CREATE TABLE "TBL_MENU_MASTER" 
   (	
    "ID" VARCHAR2(100), 
	"MENU_ID" VARCHAR2(100), 
	"NAME" VARCHAR2(1000), 
	"PARENT_ID" VARCHAR2(100), 
	"ROLE" VARCHAR2(100), 
	"FILE_NAME" VARCHAR2(1000), 
	"URL" VARCHAR2(1000), 
	"USE_YN" VARCHAR2(100) DEFAULT 'Y',
	PRIMARY KEY ("ID")	
   ); 
CREATE TABLE "TBL_USER_TYPE" 
   (	
    "USER_TYPE_ID" NUMBER, 
	"USER_TYPE" VARCHAR2(100), 
	"USER_TYPE_DESC" VARCHAR2(100)	
   );
CREATE TABLE "TBL_ROLE" 
   (	
    "ROLE_ID" VARCHAR2(100), 
	"ROLE" VARCHAR2(50), 
	"ROLE_DESC" VARCHAR2(100), 
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("ROLE_ID")	
   );

Insert into TBL_ROLE (ROLE_ID,ROLE,ROLE_DESC,CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY) values ('1','SA','System Admin',CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,null);
Insert into TBL_ROLE (ROLE_ID,ROLE,ROLE_DESC,CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY) values ('2','LA','Local Admin',CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,null);
Insert into TBL_ROLE (ROLE_ID,ROLE,ROLE_DESC,CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY) values ('3','CC','Corporate Centre User',CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,null);
Insert into TBL_ROLE (ROLE_ID,ROLE,ROLE_DESC,CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY) values ('4','C','Circle User',CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,null);
Insert into TBL_ROLE (ROLE_ID,ROLE,ROLE_DESC,CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY) values ('5','CMS','Channel Manager Supervisor',CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,null);
Insert into TBL_ROLE (ROLE_ID,ROLE,ROLE_DESC,CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY) values ('6','CMF','Channel Manager Facilitator',CURRENT_TIMESTAMP,null,CURRENT_TIMESTAMP,null);

CREATE TABLE "TBL_TERMINAL_STATUS" 
   (	
    "TERMINAL_ID" VARCHAR2(100), 
	"CIRCLE" VARCHAR2(100), 
	"KIOSK_ID" VARCHAR2(100), 
	"BRANCH_CODE" VARCHAR2(100), 
	"PASSBOOK_PRINTER_STATUS" VARCHAR2(100), 
	"CARTRIDGE_INK" VARCHAR2(100), 
	"APPLICATION_STATUS" VARCHAR2(100), 
	"ANTIVIRUS" VARCHAR2(100), 
	"AGENT_STATUS" VARCHAR2(100), 
	"LAST_RECEIVED" VARCHAR2(100), 
	"TIME_DIFF" VARCHAR2(100), 
	"VERSION" VARCHAR2(100), 
	"CALL_TYPE" VARCHAR2(100),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("TERMINAL_ID")
   );
CREATE TABLE "TBL_TICKET_CENTRE" 
   (	
    "TICKET_ID" VARCHAR2(100),
    "VENDOR" VARCHAR2(100), 	 
	"KIOSK_ID" VARCHAR2(100), 
	"BRANCH_CODE" VARCHAR2(100), 
	"CALL_CATEGORY" VARCHAR2(1000), 
	"CMS_CMF_ASSIGNED" VARCHAR2(100), 
	"CALL_LOG_DATE" DATE, 
	"STATUS_OF_COMPLAINT" VARCHAR2(100), 
	"ASSIGNED_TO_FE" VARCHAR2(100), 
	"FE_SCHEDULE" VARCHAR2(100), 
	"SEVERITY" VARCHAR2(100), 
	"CALL_SUBCATEGORY" VARCHAR2(2000), 
	"AGEING" VARCHAR2(100), 
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("TICKET_ID")	
   );
 CREATE TABLE "TBL_TICKET_HISTORY" 
   (	
    "TICKET_ID" VARCHAR2(100),
    "VENDOR" VARCHAR2(100), 	 
	"KIOSK_ID" VARCHAR2(100), 
	"BRANCH_CODE" VARCHAR2(100), 
	"CALL_CATEGORY" VARCHAR2(1000), 
	"CMS_CMF_ASSIGNED" VARCHAR2(100), 
	"CALL_LOG_DATE" DATE, 
	"STATUS_OF_COMPLAINT" VARCHAR2(100), 
	"ASSIGNED_TO_FE" VARCHAR2(100), 
	"FE_SCHEDULE" VARCHAR2(100), 
	"SEVERITY" VARCHAR2(100), 
	"CALL_SUBCATEGORY" VARCHAR2(2000), 
	"AGEING" VARCHAR2(100), 
	"CALL_TYPE" VARCHAR2(100), 
	"CLOSE_DATE" VARCHAR2(100),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("TICKET_ID")		 
   );  
CREATE TABLE "TBL_TRANSACTION_MASTER" 
   (	
    "TXN_ID" VARCHAR2(100), 
	"KIOSK_ID" VARCHAR2(100), 
	"VENDOR" VARCHAR2(100), 
	"BR_ID" VARCHAR2(100), 
	"TXN_TYPE" VARCHAR2(100), 
	"NO_OF_TXNS" VARCHAR2(100), 
	"TYPE_OF_ERROR" VARCHAR2(100),
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
   );
CREATE TABLE "TBL_USER_KIOSK_MAPPING" 
   (	
     "USER_ID" NUMBER, 
	 "PF_ID" VARCHAR2(1000),
	"KIOSK_ID" VARCHAR2(1000)
   );   
 
 CREATE TABLE "TBL_USER_PRIVILEGES " 
   (	
    "ID" VARCHAR2(100), 
	"ROLE_ID" VARCHAR2(100), 
	"PRIVILEGE" VARCHAR2(1000)
   );
create table TBL_REQUESTS
(
 "ID" NUMBER,
 "CASE_ID" VARCHAR2(100),
 "BRANCH_CODE" VARCHAR2(100),
 "KIOSK_ID" VARCHAR2(1000), 
 "VENDOR" VARCHAR2(100), 
 "CATEGORY" VARCHAR2(100), 
 "SUB_CATEGORY" VARCHAR2(100), 
 "TYPE_OF_REQUEST" VARCHAR2(100), 
 "SUBJECT" VARCHAR2(100),
 "COMMENTS" VARCHAR2(3000),
 "USER_TYPE" VARCHAR2(100),
 "REQ_CAT" VARCHAR2(100),
 "CREATED_BY" VARCHAR2(100),
 "CREATED_DATE" TIMESTAMP (6), 
 "MODIFIED_BY" VARCHAR2(100),
 "MODIFIED_DATE" TIMESTAMP (6) 
);
   
CREATE TABLE "REVINFO" 
(    
   "REV" NUMBER(10,0) NOT NULL ENABLE, 
   "REVTSTMP" NUMBER(19,0), 
   PRIMARY KEY ("REV")  
);
create table TBL_REQUESTS_AUD
(
 "REV" NUMBER(10,0) NOT NULL ENABLE, 
 "REVTYPE" NUMBER(3,0), 
 "ID" NUMBER,
 "CASE_ID" VARCHAR2(100),
 "BRANCH_CODE" VARCHAR2(100),
 "KIOSK_ID" VARCHAR2(1000), 
 "VENDOR" VARCHAR2(100), 
 "CATEGORY" VARCHAR2(100), 
 "SUB_CATEGORY" VARCHAR2(100), 
 "TYPE_OF_REQUEST" VARCHAR2(100), 
 "SUBJECT" VARCHAR2(100),
 "COMMENTS" VARCHAR2(3000),
 "USER_TYPE" VARCHAR2(100),
 "REQ_CAT" VARCHAR2(100),
 "CREATED_BY" VARCHAR2(100),
 "CREATED_DATE" TIMESTAMP (6), 
 "MODIFIED_BY" VARCHAR2(100),
 "MODIFIED_DATE" TIMESTAMP (6) 
);   
 
CREATE TABLE "TBL_SUPERVISOR" 
   (	
    "ID" NUMBER, 
	"PF_ID" VARCHAR2(1000), 
	"PF_ID_SUPERVISOR" VARCHAR2(1000),
	PRIMARY KEY ("ID")	
   );   
CREATE TABLE TBL_BRANCH_HOLIDAY
   (
    "ID" NUMBER,
	"DATE" VARCHAR2(1000 BYTE),
	"DAY" VARCHAR2(1000 BYTE),
	"NAME" VARCHAR2(1000 BYTE),
	"CIRCLE" VARCHAR2(1000 BYTE),
	"STATE" VARCHAR2(1000 BYTE),
	PRIMARY KEY ("ID")	
   );   
   
 CREATE SEQUENCE  "USER_ID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;
 CREATE SEQUENCE  "SEQ_TBL_KIOSK_MASTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;  
 CREATE SEQUENCE  "SEQ_TBL_BRANCH_MASTER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;
 CREATE SEQUENCE  "SEQ_TBL_CMS_CMF_MAPPING"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;
 CREATE SEQUENCE  "SEQ_TBL_USER_KIOSK_MAPPING"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;  
 CREATE SEQUENCE  "SEQ_TBL_REQUESTS"  MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER;
 CREATE SEQUENCE hibernate_sequence  INCREMENT BY 1  MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 1 CACHE 20;
 CREATE SEQUENCE  "SEQ_TBL_SUPERVISOR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER;

   
   
   
   
   
   
   
 
 
 
 