DROP TABLE "TBL_USER";
CREATE TABLE "TBL_USER" 
   (	
    "USER_ID" NUMBER NOT NULL, 
	"PF_ID" VARCHAR2(100) NOT NULL,	
    "USERNAME" VARCHAR2(200),
	"MAIL_ID" VARCHAR2(100), 
	"PHONENO" VARCHAR2(50), 	
	"ROLE" VARCHAR2(20), 	
	"CIRCLE" VARCHAR2(100), 
    "REPORTING_AUTHORITY_NAME" VARCHAR2(100), 
    "REPORTING_AUTHORITY_EMAIL"  VARCHAR2(100), 
	"ENABLED" VARCHAR2(1), 
	"FIRSTNAME" VARCHAR2(100), 	
	"LASTNAME" VARCHAR2(100), 
	"CREATED_BY" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP (6), 
	"MODIFIED_BY" VARCHAR2(100),
	"MODIFIED_DATE" TIMESTAMP (6),
	PRIMARY KEY ("USER_ID")	
   );