package sbi.kiosk.swayam.transactiondashboard.repository;

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import sbi.kiosk.swayam.common.entity.SwayamMigrationSummary;

@Repository
public interface TransactionDashBoardRepositoryPaging extends PagingAndSortingRepository<SwayamMigrationSummary, String>{

	Page<SwayamMigrationSummary> findAll(Pageable pageable);
	
	/*
	@Query(value="	SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK, B.MODULE MODULE,B.REGION REGION,  B.BRANCH_CODE BRANCH_CODE,"
   			+ " B.BRANCH_NAME BRANCH_NAME,   SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,  SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT,"
   			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT, SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,"
   			+ " SUM(M.CMS_TXN_CNT) CMS_TXN_CNT,  SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,  SUM(BR_TXN.MANUAL_TXNS) MANUAL_TXNS,"
   			+ "  ( CASE  WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS), 0) = 0 THEN 0  "
   			+ " ELSE ROUND(SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + SUM(BR_TXN.MANUAL_TXNS) ), 2 ) END ) "
   			+ " MIG_PRCNT FROM   TBL_BRANCH_MASTER B "
	+ "  INNER JOIN (SELECT BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  "
	+ " FROM  TBL_BRANCH_TXN_DAILY DATA2  WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
	+ " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   BRANCH_NO ) BR_TXN ON BR_TXN.BRANCH_NO = B.BRANCH_CODE "
	+ "   INNER JOIN (SELECT BRANCH_CODE, SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM( CASE VENDOR  WHEN 'LIPI'  "
	+ " THEN DATA1.NO_OF_KIOSKS   ELSE 0 END  ) LIPI_KIOSK_CNT, SUM( CASE VENDOR  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0 "
	+ "  END   ) LIPI_TXN_CNT,   SUM(  CASE VENDOR  WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS  ELSE 0   END ) FORBES_KIOSK_CNT, "
	+ "  SUM(   CASE VENDOR WHEN 'FORBES'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END   ) FORBES_TXN_CNT,SUM( CASE VENDOR  WHEN 'CMS' "
	+ "  THEN DATA1.NO_OF_KIOSKS   ELSE 0   END   ) CMS_KIOSK_CNT,  SUM( CASE VENDOR  WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS ELSE 0 "
	+ "  END ) CMS_TXN_CNT,  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS"
	//+ "     --nvl(sum(distinct data2.manual_txns),0) manual_txns   
+" FROM ( SELECT MST.BRANCH_CODE, MST.VENDOR,COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL( SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
+ "  FROM    TBL_KIOSK_MASTER MST,  TBL_SWAYAM_TXN_REPORT DTL  "
// + "    --  where mst.kiosk_id = dtl.kiosk_id( )   "
+ " WHERE  UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) )  AND "
+ " TO_DATE(TXN_DATE,'dd-mm-yyyy') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
+ " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   MST.BRANCH_CODE,  MST.VENDOR  ORDER BY  MST.BRANCH_CODE, "
+ " MST.VENDOR ) DATA1"
// + "  --where data1.branch_code = data2.branch_no"
+ " GROUP BY   DATA1.BRANCH_CODE ORDER BY DATA1.BRANCH_CODE ) M ON B.BRANCH_CODE = M.BRANCH_CODE GROUP BY  B.CRCL_NAME, "
+ "  B.NETWORK, B.MODULE, B.REGION, B.BRANCH_CODE, B.BRANCH_NAME" ,
nativeQuery=true,countQuery ="SELECT  count( B.BRANCH_CODE) from  TBL_BRANCH_MASTER B   INNER JOIN (SELECT BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  "
		+ " FROM  TBL_BRANCH_TXN_DAILY DATA2  WHERE "
		+ "  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
		+ " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   BRANCH_NO ) BR_TXN ON BR_TXN.BRANCH_NO = B.BRANCH_CODE "
		+ "   INNER JOIN (SELECT BRANCH_CODE, SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM( CASE VENDOR  WHEN 'LIPI'  "
		+ " THEN DATA1.NO_OF_KIOSKS   ELSE 0 END  ) LIPI_KIOSK_CNT, SUM( CASE VENDOR  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0 "
		+ "  END   ) LIPI_TXN_CNT,   SUM(  CASE VENDOR  WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS  ELSE 0   END ) FORBES_KIOSK_CNT, "
		+ "  SUM(   CASE VENDOR WHEN 'FORBES'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END   ) FORBES_TXN_CNT,SUM( CASE VENDOR  WHEN 'CMS' "
		+ "  THEN DATA1.NO_OF_KIOSKS   ELSE 0   END   ) CMS_KIOSK_CNT,  SUM( CASE VENDOR  WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS ELSE 0 "
		+ "  END ) CMS_TXN_CNT,  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS"
		//+ "     --nvl(sum(distinct data2.manual_txns),0) manual_txns   
  +" FROM ( SELECT MST.BRANCH_CODE, MST.VENDOR,COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL( SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
  + "  FROM    TBL_KIOSK_MASTER MST,  TBL_SWAYAM_TXN_REPORT DTL  "
 // + "    --  where mst.kiosk_id = dtl.kiosk_id( )   "
  + " WHERE  UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) )  AND  TO_DATE(TXN_DATE,'dd-mm-yyyy') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
  + " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   MST.BRANCH_CODE,  MST.VENDOR  ORDER BY  MST.BRANCH_CODE, "
  + " MST.VENDOR ) DATA1"
 // + "  --where data1.branch_code = data2.branch_no"
  + " GROUP BY   DATA1.BRANCH_CODE ORDER BY DATA1.BRANCH_CODE ) M ON B.BRANCH_CODE = M.BRANCH_CODE GROUP BY  B.CRCL_NAME, "
  + "  B.NETWORK, B.MODULE, B.REGION, B.BRANCH_CODE, B.BRANCH_NAME")*/
	
	//changes
	

	/* Commented by Manisha on 20-01-2021
	 * @Query(
	 * value="SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, " +
	 * " B.REGION REGION,B.BRANCH_CODE BRANCH_CODE,B.BRANCH_NAME BRANCH_NAME, " +
	 * " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, " +
	 * " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
	 * + " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, " +
	 * " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
	 * +
	 * " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
	 * +
	 * "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
	 * + "  2  ) " + "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT" +
	 * "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
	 * +
	 * " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
	 * + " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN " +
	 * " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, " +
	 * "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' " +
	 * "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR " +
	 * "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT," +
	 * " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 " +
	 * "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN " +
	 * " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
	 * + " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR " +
	 * "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, " +
	 * "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
	 * +
	 * "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
	 * + " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL " +
	 * " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TO_DATE(TXN_DATE,'dd-mm-yyyy') "
	 * + " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND " +
	 * " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
	 * + " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
	 * + " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE " +
	 * " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME "
	 * , nativeQuery=true, countQuery
	 * =" SELECT count(B.BRANCH_CODE) AS BRANCH_CODE ,B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
	 * + " B.REGION REGION,B.BRANCH_NAME BRANCH_NAME, " +
	 * " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, " +
	 * " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
	 * + " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, " +
	 * " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
	 * +
	 * " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
	 * +
	 * "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
	 * + "  2  ) " + "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT "
	 * +
	 * "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
	 * +
	 * " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
	 * + " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN " +
	 * " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, " +
	 * "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' " +
	 * "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR " +
	 * "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT, " +
	 * " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 " +
	 * "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN " +
	 * " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
	 * + " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR " +
	 * "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, " +
	 * "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
	 * +
	 * "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
	 * + " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL " +
	 * " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TO_DATE(TXN_DATE,'dd-mm-yyyy') "
	 * + " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND " +
	 * " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
	 * + " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
	 * + " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE " +
	 * " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME"
	 * )
	 */
	@Query(value="SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
			+ " B.REGION REGION,B.BRANCH_CODE BRANCH_CODE,B.BRANCH_NAME BRANCH_NAME, "
			+ " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, "
			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
			+ " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, "
			+ " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
			+ " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
			+ "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
			+ "  2  ) "
			+ "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT"
			+ "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
			+ " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
			+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN "
			+ " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, "
			+ "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' "
			+ "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR "
			+ "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT,"
			+ " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 "
			+ "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN "
			+ " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
			+ " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR "
			+ "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, "
			+ "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
			+ "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
			+ " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL "
			+ " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TXN_DATE "
			+ " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
			+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
			+ " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
			+ " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE "
			+ " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME ",
		nativeQuery=true,
		countQuery =" SELECT count(B.BRANCH_CODE) AS BRANCH_CODE ,B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
			+ " B.REGION REGION,B.BRANCH_NAME BRANCH_NAME, "
			+ " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, "
			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
			+ " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, "
			+ " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
			+ " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
			+ "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
			+ "  2  ) "
			+ "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT "
				+ "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
				+ " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
				+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN "
				+ " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, "
				+ "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' "
				+ "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR "
				+ "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT, "
				+ " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 "
				+ "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN "
				+ " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
				+ " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR "
				+ "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, "
				+ "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
				+ "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
				+ " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL "
				+ " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TXN_DATE "
				+ " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
				+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
				+ " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
				+ " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE "
				+ " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME")
	
	
	Page<SwayamMigrationSummary> findByDate(@Param("fromdate") String fromdate,@Param("todate") String todate,Pageable pageable);
	
	/* Commented by Manisha on 20-01-2021
	 * @Query(
	 * value="SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, " +
	 * " B.REGION REGION,B.BRANCH_CODE BRANCH_CODE,B.BRANCH_NAME BRANCH_NAME, " +
	 * " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, " +
	 * " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
	 * + " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, " +
	 * " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
	 * +
	 * " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
	 * +
	 * "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
	 * + "  2  ) " + "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT" +
	 * "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
	 * +
	 * " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
	 * + " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN " +
	 * " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, " +
	 * "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' " +
	 * "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR " +
	 * "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT," +
	 * " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 " +
	 * "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN " +
	 * " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
	 * + " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR " +
	 * "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, " +
	 * "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
	 * +
	 * "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
	 * + " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL " +
	 * " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TO_DATE(TXN_DATE,'dd-mm-yyyy') "
	 * + " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND " +
	 * " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
	 * + " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
	 * + " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE " +
	 * " AND (B.CRCL_NAME=:searchText OR B.NETWORK=:searchText OR B.MODULE=:searchText OR B.REGION=:searchText OR B.BRANCH_CODE=:searchText OR B.BRANCH_NAME=:searchText)"
	 * +
	 * " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME "
	 * , nativeQuery=true, countQuery
	 * ="SELECT count(B.BRANCH_CODE) AS BRANCH_CODE ,B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
	 * + " B.REGION REGION,B.BRANCH_NAME BRANCH_NAME, " +
	 * " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, " +
	 * " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
	 * + " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, " +
	 * " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
	 * +
	 * " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
	 * +
	 * "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
	 * + "  2  ) " + "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT "
	 * +
	 * "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
	 * +
	 * " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
	 * + " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN " +
	 * " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, " +
	 * "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' " +
	 * "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR " +
	 * "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT, " +
	 * " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 " +
	 * "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN " +
	 * " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
	 * + " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR " +
	 * "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, " +
	 * "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
	 * +
	 * "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
	 * + " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL " +
	 * " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TO_DATE(TXN_DATE,'dd-mm-yyyy') "
	 * + " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND " +
	 * " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
	 * + " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
	 * + " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE " +
	 * " AND (B.CRCL_NAME=:searchText OR B.NETWORK=:searchText OR B.MODULE=:searchText OR B.REGION=:searchText OR B.BRANCH_CODE=:searchText OR B.BRANCH_NAME=:searchText)"
	 * +
	 * " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME"
	 * )
	 */

	@Query(value="SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
			+ " B.REGION REGION,B.BRANCH_CODE BRANCH_CODE,B.BRANCH_NAME BRANCH_NAME, "
			+ " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, "
			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
			+ " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, "
			+ " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
			+ " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
			+ "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
			+ "  2  ) "
			+ "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT"
			+ "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
			+ " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
			+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN "
			+ " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, "
			+ "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' "
			+ "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR "
			+ "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT,"
			+ " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 "
			+ "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN "
			+ " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
			+ " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR "
			+ "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, "
			+ "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
			+ "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
			+ " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL "
			+ " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TXN_DATE"
			+ " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
			+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
			+ " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
			+ " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE "
			+ " AND (B.CRCL_NAME=:searchText OR B.NETWORK=:searchText OR B.MODULE=:searchText OR B.REGION=:searchText OR B.BRANCH_CODE=:searchText OR B.BRANCH_NAME=:searchText)"
			+ " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME ",
		nativeQuery=true,
		countQuery ="SELECT count(B.BRANCH_CODE) AS BRANCH_CODE ,B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
			+ " B.REGION REGION,B.BRANCH_NAME BRANCH_NAME, "
			+ " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, "
			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
			+ " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, "
			+ " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
			+ " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
			+ "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
			+ "  2  ) "
			+ "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT "
				+ "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
				+ " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
				+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN "
				+ " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, "
				+ "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' "
				+ "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR "
				+ "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT, "
				+ " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 "
				+ "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN "
				+ " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
				+ " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR "
				+ "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, "
				+ "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
				+ "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
				+ " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL "
				+ " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TXN_DATE "
				+ " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
				+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
				+ " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
				+ " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE "
				+ " AND (B.CRCL_NAME=:searchText OR B.NETWORK=:searchText OR B.MODULE=:searchText OR B.REGION=:searchText OR B.BRANCH_CODE=:searchText OR B.BRANCH_NAME=:searchText)"
				+ " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME")
	
	Page<SwayamMigrationSummary> findByFromDateSearchText(@Param("fromdate") String fromdate,@Param("todate") String todate,@Param("searchText") String searchText,Pageable pageable);

/*
	@Query(value="	SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK, B.MODULE MODULE,B.REGION REGION,  B.BRANCH_CODE BRANCH_CODE,"
   			+ " B.BRANCH_NAME BRANCH_NAME,   SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,  SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT,"
   			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT, SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,"
   			+ " SUM(M.CMS_TXN_CNT) CMS_TXN_CNT,  SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,  SUM(BR_TXN.MANUAL_TXNS) MANUAL_TXNS,"
   			+ "  ( CASE  WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS), 0) = 0 THEN 0  "
   			+ " ELSE ROUND(SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + SUM(BR_TXN.MANUAL_TXNS) ), 2 ) END ) "
   			+ " MIG_PRCNT FROM   TBL_BRANCH_MASTER B "
	+ "  INNER JOIN (SELECT BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  "
	+ " FROM  TBL_BRANCH_TXN_DAILY DATA2  WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
	+ " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   BRANCH_NO ) BR_TXN ON BR_TXN.BRANCH_NO = B.BRANCH_CODE "
	+ "   INNER JOIN (SELECT BRANCH_CODE, SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM( CASE VENDOR  WHEN 'LIPI'  "
	+ " THEN DATA1.NO_OF_KIOSKS   ELSE 0 END  ) LIPI_KIOSK_CNT, SUM( CASE VENDOR  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0 "
	+ "  END   ) LIPI_TXN_CNT,   SUM(  CASE VENDOR  WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS  ELSE 0   END ) FORBES_KIOSK_CNT, "
	+ "  SUM(   CASE VENDOR WHEN 'FORBES'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END   ) FORBES_TXN_CNT,SUM( CASE VENDOR  WHEN 'CMS' "
	+ "  THEN DATA1.NO_OF_KIOSKS   ELSE 0   END   ) CMS_KIOSK_CNT,  SUM( CASE VENDOR  WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS ELSE 0 "
	+ "  END ) CMS_TXN_CNT,  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS"
	//+ "     --nvl(sum(distinct data2.manual_txns),0) manual_txns   
+" FROM ( SELECT MST.BRANCH_CODE, MST.VENDOR,COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL( SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
+ "  FROM    TBL_KIOSK_MASTER MST,  TBL_SWAYAM_TXN_REPORT DTL  "
// + "    --  where mst.kiosk_id = dtl.kiosk_id( )   "
+ " WHERE  UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) )  AND "
+ " TO_DATE(TXN_DATE,'dd-mm-yyyy') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
+ " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   MST.BRANCH_CODE,  MST.VENDOR  ORDER BY  MST.BRANCH_CODE, "
+ " MST.VENDOR ) DATA1"
// + "  --where data1.branch_code = data2.branch_no"
+ " GROUP BY   DATA1.BRANCH_CODE ORDER BY DATA1.BRANCH_CODE ) M ON B.BRANCH_CODE = M.BRANCH_CODE GROUP BY  B.CRCL_NAME, "
+ "  B.NETWORK, B.MODULE, B.REGION, B.BRANCH_CODE, B.BRANCH_NAME" ,
nativeQuery=true,countQuery ="SELECT  count( B.BRANCH_CODE) from  TBL_BRANCH_MASTER B   INNER JOIN (SELECT BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  "
		+ " FROM  TBL_BRANCH_TXN_DAILY DATA2  WHERE "
		+ "  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
		+ " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   BRANCH_NO ) BR_TXN ON BR_TXN.BRANCH_NO = B.BRANCH_CODE "
		+ "   INNER JOIN (SELECT BRANCH_CODE, SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM( CASE VENDOR  WHEN 'LIPI'  "
		+ " THEN DATA1.NO_OF_KIOSKS   ELSE 0 END  ) LIPI_KIOSK_CNT, SUM( CASE VENDOR  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0 "
		+ "  END   ) LIPI_TXN_CNT,   SUM(  CASE VENDOR  WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS  ELSE 0   END ) FORBES_KIOSK_CNT, "
		+ "  SUM(   CASE VENDOR WHEN 'FORBES'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END   ) FORBES_TXN_CNT,SUM( CASE VENDOR  WHEN 'CMS' "
		+ "  THEN DATA1.NO_OF_KIOSKS   ELSE 0   END   ) CMS_KIOSK_CNT,  SUM( CASE VENDOR  WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS ELSE 0 "
		+ "  END ) CMS_TXN_CNT,  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS"
		//+ "     --nvl(sum(distinct data2.manual_txns),0) manual_txns   
  +" FROM ( SELECT MST.BRANCH_CODE, MST.VENDOR,COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL( SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
  + "  FROM    TBL_KIOSK_MASTER MST,  TBL_SWAYAM_TXN_REPORT DTL  "
 // + "    --  where mst.kiosk_id = dtl.kiosk_id( )   "
  + " WHERE  UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) )  AND  TO_DATE(TXN_DATE,'dd-mm-yyyy') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) "
  + " AND TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )    GROUP BY   MST.BRANCH_CODE,  MST.VENDOR  ORDER BY  MST.BRANCH_CODE, "
  + " MST.VENDOR ) DATA1"
 // + "  --where data1.branch_code = data2.branch_no"
  + " GROUP BY   DATA1.BRANCH_CODE ORDER BY DATA1.BRANCH_CODE ) M ON B.BRANCH_CODE = M.BRANCH_CODE GROUP BY  B.CRCL_NAME, "
  + "  B.NETWORK, B.MODULE, B.REGION, B.BRANCH_CODE, B.BRANCH_NAME")*/

// changes


	/* commented by Manisha on 20-01-2021
	 * @Query(
	 * value="	SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, " +
	 * " B.REGION REGION,B.BRANCH_CODE BRANCH_CODE,B.BRANCH_NAME BRANCH_NAME, " +
	 * " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, " +
	 * " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
	 * + " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, " +
	 * " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
	 * +
	 * " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
	 * +
	 * "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
	 * + "  2  ) " + "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT" +
	 * "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
	 * +
	 * " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
	 * + " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN " +
	 * " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, " +
	 * "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' " +
	 * "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR " +
	 * "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT," +
	 * " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 " +
	 * "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN " +
	 * " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
	 * + " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR " +
	 * "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, " +
	 * "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
	 * +
	 * "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
	 * + " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL " +
	 * " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TO_DATE(TXN_DATE,'dd-mm-yyyy') "
	 * + " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND " +
	 * " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
	 * + " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
	 * + " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE " +
	 * " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME "
	 * , nativeQuery=true, countQuery
	 * =" SELECT count(B.BRANCH_CODE) AS BRANCH_CODE ,B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
	 * + " B.REGION REGION,B.BRANCH_NAME BRANCH_NAME, " +
	 * " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, " +
	 * " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
	 * + " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, " +
	 * " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
	 * +
	 * " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
	 * +
	 * "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
	 * + "  2  ) " + "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT "
	 * +
	 * "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
	 * +
	 * " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
	 * + " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN " +
	 * " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, " +
	 * "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' " +
	 * "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR " +
	 * "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT, " +
	 * " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 " +
	 * "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN " +
	 * " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
	 * + " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR " +
	 * "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, " +
	 * "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
	 * +
	 * "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
	 * + " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL " +
	 * " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TO_DATE(TXN_DATE,'dd-mm-yyyy') "
	 * + " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND " +
	 * " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
	 * + " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
	 * + " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE " +
	 * " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME"
	 * )
	 */

	@Query(value="	SELECT B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
			+ " B.REGION REGION,B.BRANCH_CODE BRANCH_CODE,B.BRANCH_NAME BRANCH_NAME, "
			+ " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, "
			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
			+ " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, "
			+ " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
			+ " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
			+ "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
			+ "  2  ) "
			+ "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT"
			+ "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
			+ " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
			+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN "
			+ " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, "
			+ "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' "
			+ "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR "
			+ "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT,"
			+ " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 "
			+ "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN "
			+ " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
			+ " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR "
			+ "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, "
			+ "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
			+ "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
			+ " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL "
			+ " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TXN_DATE "
			+ " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
			+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
			+ " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
			+ " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE "
			+ " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME ",
		nativeQuery=true,
		countQuery =" SELECT count(B.BRANCH_CODE) AS BRANCH_CODE ,B.CRCL_NAME CRCL_NAME,B.NETWORK NETWORK,B.MODULE MODULE, "
			+ " B.REGION REGION,B.BRANCH_NAME BRANCH_NAME, "
			+ " SUM(M.LIPI_KIOSK_CNT) LIPI_KIOSK_CNT,SUM(M.LIPI_TXN_CNT) LIPI_TXN_CNT, "
			+ " SUM(M.FORBES_KIOSK_CNT) FORBES_KIOSK_CNT,SUM(M.FORBES_TXN_CNT) FORBES_TXN_CNT, "
			+ " SUM(M.CMS_KIOSK_CNT) CMS_KIOSK_CNT,SUM(M.CMS_TXN_CNT) CMS_TXN_CNT, "
			+ " SUM(M.TOTAL_SWAYAM_TXNS) TOTAL_SWAYAM_TXNS,NVL(SUM(BR_TXN.MANUAL_TXNS),0) MANUAL_TXNS, "
			+ " (  CASE   WHEN NVL( SUM(M.TOTAL_SWAYAM_TXNS),     0 ) = 0 THEN 0  ELSE ROUND( "
			+ "   SUM(M.TOTAL_SWAYAM_TXNS) * 100 / (SUM(M.TOTAL_SWAYAM_TXNS) + NVL(SUM(BR_TXN.MANUAL_TXNS),0)  ), "
			+ "  2  ) "
			+ "END) MIG_PRCNT FROM TBL_BRANCH_MASTER B LEFT JOIN (  SELECT "
				+ "  BRANCH_NO,NVL(SUM(NO_OF_ACCOUNTS),0) MANUAL_TXNS  FROM TBL_BRANCH_TXN_DAILY DATA2 "
				+ " WHERE  TO_DATE(LAST_PBK_DT,'yyyy-mm-dd') BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
				+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') )  GROUP BY   BRANCH_NO) BR_TXN "
				+ " ON BR_TXN.BRANCH_NO = B.BRANCH_CODE INNER JOIN (SELECT BRANCH_CODE, "
				+ "  SUM(NO_OF_KIOSKS) TOTAL_SWAYAM_KIOSKS, SUM(CASE VENDOR   WHEN 'LIPI' "
				+ "  THEN DATA1.NO_OF_KIOSKS  ELSE 0  END) LIPI_KIOSK_CNT, SUM(CASE VENDOR "
				+ "  WHEN 'LIPI'   THEN DATA1.SWAYAM_TXNS  ELSE 0  END) LIPI_TXN_CNT, "
				+ " SUM(CASE VENDOR WHEN 'FORBES'   THEN DATA1.NO_OF_KIOSKS ELSE 0 "
				+ "  END ) FORBES_KIOSK_CNT,SUM(CASE VENDOR   WHEN 'FORBES'   THEN "
				+ " DATA1.SWAYAM_TXNS ELSE 0  END ) FORBES_TXN_CNT,  SUM(CASE VENDOR  WHEN 'CMS' "
				+ " THEN DATA1.NO_OF_KIOSKS  ELSE 0  END ) CMS_KIOSK_CNT,SUM(CASE VENDOR "
				+ "   WHEN 'CMS'   THEN DATA1.SWAYAM_TXNS   ELSE 0  END) CMS_TXN_CNT, "
				+ "  SUM(SWAYAM_TXNS) TOTAL_SWAYAM_TXNS  FROM  ( SELECT  MST.BRANCH_CODE, MST.VENDOR, "
				+ "  COUNT(DISTINCT MST.KIOSK_ID) NO_OF_KIOSKS, NVL(SUM(DTL.NO_OF_TXNS), 0 ) SWAYAM_TXNS "
				+ " FROM TBL_KIOSK_MASTER MST,TBL_SWAYAM_TXN_REPORT DTL "
				+ " WHERE UPPER(MST.KIOSK_ID) = UPPER(DTL.KIOSK_ID(+) ) AND TXN_DATE "
				+ " BETWEEN TRUNC(TO_DATE(:fromdate,'dd-mm-yyyy') ) AND "
				+ " TRUNC(TO_DATE(:todate,'dd-mm-yyyy') ) GROUP BY MST.BRANCH_CODE,MST.VENDOR "
				+ " ORDER BY MST.BRANCH_CODE,MST.VENDOR) DATA1   GROUP BY DATA1.BRANCH_CODE "
				+ " ORDER BY DATA1.BRANCH_CODE) M ON B.BRANCH_CODE = M.BRANCH_CODE "
				+ " GROUP BY B.CRCL_NAME,B.NETWORK,B.MODULE,B.REGION,B.BRANCH_CODE,B.BRANCH_NAME")

	List<SwayamMigrationSummary> findAllByDate(@Param("fromdate") String fromdate,@Param("todate") String todate);

	// 12c
		//@Query(value="select to_date(last_pbk_dt,'yyyy-mm-dd') from tbl_branch_txn_daily order by last_pbk_dt desc fetch first 1 row only ",nativeQuery = true )
		
// new query
		@Query(value="select to_char(to_date(last_pbk_dt,'yyyy-mm-dd'),'dd-mm-yyyy') from tbl_branch_txn_daily order by last_pbk_dt desc fetch first 1 row only",nativeQuery = true)
		//for 11g
	//	@Query(value="select to_char(end_dttm,'dd-Mon-yy hh24:mm:ss') from  tbl_audit_job where job_name='TBL_SWAYAM_TXN_DAILY' and rownum <= 1 order by end_dttm desc ",nativeQuery = true )
		String findCurrentDateAuditJob();
}
